### PR TITLE
Add 2D Shape features

### PR DESCRIPTION
**Pull request by JoostJM**
Add a new featureclass implementing shape features describing a 2D shape.
This class can only be extracted if `force2D = True` and the size of the bounding box is 1 in the dimension specified by `force2Ddimension` (i.e. it must be a truly 2D segmentation)

This featureclass is therefore not enabled by default.

cc @Radiomics/developers

### CODE REVIEW

**Comment by fedorov** [comment]
> the size of the bounding box is 1 in the dimension specified by force2Ddimension (i.e. it must be a truly 2D segmentation)

I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

**Comment by pieper** [comment]
I don't think a spacing of zero is a good idea.  I would think we can come up with a reasonable definition of grid samples that gracefully handles any combination of dimensions and spacings in any dimension without becoming degenerate.

**Comment by fedorov** [comment]
Definitely - I think it is better if the tool allowed processing of true 2d images. I suggested 0 z spacing in case we want to maintain the current convention that the input is always a 3d ITK image.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Comment by JoostJM** [comment]
> I would say the input is "truly 2D" if the ITK image passed as input is a 2D image, or perhaps if the spacing in z dimension is 0. Otherwise the definition can be ambiguous.

Very true, and would nicely help those users that use 2D input formats (e.g. PNG; though it does not address the multiple channels issue). On the other hand, it is likely that there are also users who have 3D input image data, but only single-slice segmentations. Those are also really 2D shapes (even though the real-world shape is 3D), but there it is more likely that dimensionality of the input data is 3D.

By the way, the latter also holds true for 2D DICOM (e.g. x-ray, mammography). ITK will read this in as 3D data, with size 1 in a certain dimension.

**Pull request merged**
