### PR TITLE
making it python 3 compatible_REVISED

### PR DESCRIPTION
**Pull request by JoostJM**
> without breaking the python 2 compatibility (#178), adding the future imports to keep others clean and behavior particularly division consistent.
> 
> The current changes should change or break nothing with python 2 execution and only make the code itself runnable on 3.

supersedes #188 

Additional changes to previous PR:

- Rebased on latest master reflecting changes by #190 and #191
- Re-enabled py3k support in continuous testing

cc @Radiomics/developers, @kmader

### CODE REVIEW

**Comment by jcfr** [comment]
@JoostJM  I ended up working on this earlier tonight. I will push the topic shortly.

**Comment by jcfr** [comment]
Let's also note that my topic is based on the current master

**Comment by JoostJM** [comment]
@jcfr Great! Also, currently the python 3 tests are failing for python 3.3, python 3.4 and higher work. The error is that the test try to install the latest version of numpy (as the requirement is >=1.9.2). However, numpy 1.12.0 requires python 2.7 or python >= 3.4.

**Comment by JoostJM** [comment]
superseded by #196

**Pull request closed without merging**
