### PR TITLE
Add pandas

### PR DESCRIPTION
**Pull request by JoostJM**
Add use of pandas to handle data in PyRadiomics

Affects all data handling in the feature base class and feature extractor, which now passes the calculated features as a pandas Series with the feature names as labels.
Change testing to load baseline as a pandas dataframe and also process/check/store results in a pandas DataFrame.

Update both scripts and `batchprocessing.py` to use pandas. Results are now stored in a pandas DataFrame and only written to disk upon completion of the extraction. This ensures that all calculated features are written, and writes "NaN" for features that failed or produced a NaN value.

Update documentation to reflect different methods for data handling.

### CODE REVIEW

**Comment by JoostJM** [comment]
Addresses #189

**Comment by JoostJM** [comment]
Even though returned type after extraction is now a pandas Series, no recoding of scripts is required, as the Series can be used similarly to a dictionary. For this, I tested `six.iteritems` and `keys()`, which worked as expected. I did change the batch scripts to better profit from the additional functionality of pandas though.

**Comment by fedorov** [comment]
I think @blezek has a lot of experience with pandas - would be great if he could review this one!

**Comment by JoostJM** [comment]
The changes in this PR up to now are to switch data handling to pandas, without extending on the functionality. I did not add additional functionality, such as storing in HDF5, because I first want to make sure the current functionality of PyRadiomics is preserved, before adding new things.

**Comment by blezek** [comment]
Changes look good.  My only concern is the list of requirements for pyradiomics is getting longer.  Since Pandas isn't critical for processing, it may make sense to move it to a `util` module, much like `vtk` has the `numpy` conversion in a optional module.

**Comment by JoostJM** [comment]
@blezek, I agree it is yet another dependency. This also made me decide not to implement the hdf5 support, as this also need an additional dependency.
By putting pandas in a separate `util` module, do you mean that inside pyradiomics it is kept as dictionaries and only converted to pandas if requested by the user?

**Comment by blezek** [comment]
@JoostJM Yes, I think that would be nice, or if you saved the final conversion until right at output time, it could be an optional output,i.e. `output_as_pandas=True`

I really don't have strong feelings on this one way or another, just hate to see Pandas being a requirement for a nice to have, but minor feature.

**Comment by pieper** [comment]
I agree with Dan - my impression is that the conversion to pandas should be
pretty straightforward as a last step so it's not really a dependency we
need.  It would be different if we had a reason to use pandas internally to
represent or work with the feature values themselves.

**Comment by JoostJM** [comment]
@pieper, in this PR I did use pandas more extensively, mainly to simplify the reading / storing and use of baseline when testing the features. Although this is somewhat simpler, and better guarantees everything is written out correctly, it is not necessary to run the tests, and if tests pass, output is also identical.

Therefore, I made a revised PR, where pandas is just an optional feature.

**Comment by JoostJM** [comment]
Superseded by #228

**Pull request closed without merging**
