### PR TITLE
BUG: Fix missing packages in Dockerfile

### PR DESCRIPTION
**Pull request by JoostJM**
To enable local binary pattern 2D and 3D, scipy, scikit-image and trimesh are additionally required, but these are not mentioned in the requirements (to allow installing without these packages).

To enable these filters in the CLI-docker, add pip install lines for these packages to the dockerfile.

### CODE REVIEW

**Comment by JoostJM** [comment]
This update builds successfully on dockerhub (tag Test): [Docker container](https://hub.docker.com/r/joostjm/pyradiomics/)

**Comment by JoostJM** [comment]
Fixes #388

**Comment by fedorov** [comment]
@JoostJM it looks good to me, but why don't we just list those packages in `requirements.txt`? I am probably missing something basic here, right?

**Comment by JoostJM** [comment]
@fedorov, the reason I don't want to list them in requirements.txt is because scipy is very difficult to install on windows. So I wrote the code in such a way that it works without those packages, except for the for the part using those packages of course.

**Pull request merged**
