### PR TITLE
WIP: Add Dockerfile

### PR DESCRIPTION
**Pull request by fedorov**
This is initial version of the Dockerfile for pyradiomics, it is functional and can be accessed from Docker Hub with `docker pull fedorov/pyradiomics`. The approach follows Dockerfile as done in http://github.com/qiicr/dcmqi, in turn derived from the work by @thewtex in https://blog.kitware.com/how-to-build-distributable-c-executables-for-linux-with-docker/.

Let's discuss how to move forward with this, but from my discussions within QIN and ITCR, it will be extremely helpful for us to provide this docker image to facilitate participation in the community activities.

Things remaining to do:
- [ ] add documentation (similar to https://qiicr.gitbooks.io/dcmqi-guide/content/user_guide/docker.html#usage)
- [ ] provide access to both pyradiomics and pyradiomicsbatch (or make one script addressing both use cases)
- [ ] separate docker image with jupyter interface

### CODE REVIEW

**Comment by thewtex** [comment]
:+1:

**Comment by kmader** [comment]
I guess I could see even having a third docker file here with a Jupyter-based interface for more interactive usage (just requires forwarding of one port and then you can use a web-browser instead of a command line). This is probably enough of a change that it wouldn't make sense to try and put it all in the same image and maybe an image that inherits from this would be better

**Comment by fedorov** [comment]
@kmader great idea! I will experiment with that.

**Comment by fedorov** [comment]
@kmader see the work @blezek did with jupyter and pyradiomics - it might be what you were looking for: https://github.com/blezek/pyradiomics/tree/add-docker!

**Comment by blezek** [comment]
@fedorov & @kmader, I added 2 new examples to the Docker, just to help someone new to Radiomics.  Would appreciate any comments or suggestions.

 https://github.com/blezek/pyradiomics/tree/add-docker

**Comment by fedorov** [comment]
@Radiomics/developers how about we merge @blezek contribution as a replacement for this current PR?

**Comment by blezek** [comment]
@fedorov, another suggestion is to create a Radiomics organization on http://dockerhub.com and auto-build the dockers when this repo changes.

**Comment by fedorov** [comment]
> another suggestion is to create a Radiomics organization

@blezek I agree - I thought @jcfr already created one, but maybe not - we should definitely do it!

**Comment by pieper** [comment]
Here's a pdf of the notebooks that @blezek is working on - you can see what it looks like without needing to install docker etc.

https://drive.google.com/file/d/0Bygzw56l1ZC-ZG1LVHBYTGZvcVl3ZEZGTm5OejFMTnVKXzc0/view?usp=sharing

**Comment by fedorov** [comment]
@JoostJM or @hugoaerts - can you create the organization for radiomics on Docker Hub? I could do it, but I think it would be better if one of you does to make sure that the lead developer/PI has access credentials to manage it. It looks like "radiomics" organization on Docker Hub is not claimed yet.

**Comment by pieper** [comment]
Grab it quick!

**Comment by JoostJM** [comment]
> Grab it quick!

[Done](https://hub.docker.com/r/radiomics/)

**Comment by pieper** [comment]
👍

**Comment by fedorov** [comment]
@blezek do you mind making a pull request with your docker work?

**Comment by blezek** [comment]
@fedorov No problem.  I'll rebase and create a pull request soon.  @JoostJM could set up DockerHub to auto-build the dockers.  I figured out that I don't have GitHub developer access to pyradiomics, so I can't configure it (shouldn't be me anyway).

**Pull request merged**
